### ISSUE TITLE
Introduce a predicate for box.value check

### ISSUE THREAD

**Issue by greenhat** [robkorn/ergo-utilities-rust#2]
## Motivation
To allow complex checks that might require registers and/or tokens analysis.

## Implementation details
Ideally, the whole box should be passed to such a predicate.

**Comment by robkorn** [comment]
Using a whole box for a single verification predicate is now implemented in latest commits: https://github.com/robkorn/ergo-utilities-rust/commit/776609f0d9ecf0a67e4e1cb1f2aa2ed3f7794244
